import sqlite3

try:
    con =sqlite3.connect("meu_banco.db")
    cur = con.cursor()
    # cur.execute("CREATE TABLE pessoa(id, nome, idade, cpf)")
   # cur.execute("INSERT INTO  pessoa VALUES(1, 'Beatrice', 20, '123.456.789-10')")
    cur.execute("INSERT INTO  pessoa VALUES(1, 'Piter', 12, '123.456.789-11')")
   # cur.execute("INSERT INTO  pessoa VALUES(1, 'Peter', 17, '123.456.789-11')")
    #cur.execute("INSERT INTO  pessoa VALUES(1, 'Dan', 09, '123.456.789-11')")
   # cur.execute("INSERT INTO  pessoa VALUES(1, 'Marck', 14, '123.456.789-11')")
    #cur.execute("INSERT INTO  pessoa VALUES(1, 'Zick', 31, '123.456.789-11')")
    #cur.execute("INSERT INTO  pessoa VALUES(1, 'Bel', 3, '123.456.789-11')")
   # cur.execute("INSERT INTO  pessoa VALUES(1, 'Zola', 16, '123.456.789-11')")
    #cur.execute("INSERT INTO  pessoa VALUES(1, 'Emma', 15, '123.456.789-11')")
    #cur.execute("INSERT INTO  pessoa VALUES(1, 'Robin', 13, '123.456.789-11')")
    # res = cur.execute("SELECT  * FROM  pessoa")
    # cur.execute("DELETE FROM pessoa WHERE id = 1")
    # con.commit()
    #cur.close
    # pessoas = res.fetchone()
    # print(pessoas)
    con.commit()

except ConnectionRefusedError as c:
    print('Erro de conex√£o com o banco.')
    
